-- MySQL Script generated by MySQL Workbench
-- Fri Aug 20 12:04:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `name` TEXT NULL,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data_produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`data_produk` (
  `id` INT NOT NULL,
  `nama_produk` VARCHAR(45) NULL,
  `harga_produk` DECIMAL NULL,
  `deskirpsi_produk` TEXT NULL,
  `slug` VARCHAR(45) NULL,
  `tanggal_input` TIMESTAMP NULL,
  `last_update` TIMESTAMP NULL,
  `status` INT(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_produk` (
  `id_produk` INT(11) NOT NULL,
  `stock` INT(11) NULL,
  `data_produk_id` INT NOT NULL,
  PRIMARY KEY (`id_produk`),
  INDEX `fk_stock_produk_data_produk1_idx` (`data_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_produk_data_produk1`
    FOREIGN KEY (`data_produk_id`)
    REFERENCES `mydb`.`data_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ketegori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ketegori` (
  `idketegori` INT(11) NOT NULL,
  `nama_kategori` VARCHAR(50) NULL,
  `icon` VARCHAR(45) NULL,
  `slug` VARCHAR(45) NULL,
  `data_produk_id` INT NOT NULL,
  PRIMARY KEY (`idketegori`),
  INDEX `fk_ketegori_data_produk1_idx` (`data_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_ketegori_data_produk1`
    FOREIGN KEY (`data_produk_id`)
    REFERENCES `mydb`.`data_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`img_produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`img_produk` (
  `id` INT NOT NULL,
  `img` LONGTEXT NULL,
  `data_produk_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_img_produk_data_produk1_idx` (`data_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_img_produk_data_produk1`
    FOREIGN KEY (`data_produk_id`)
    REFERENCES `mydb`.`data_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chart` (
  `idchart` INT NOT NULL,
  `data_produk_id` INT NOT NULL,
  PRIMARY KEY (`idchart`),
  INDEX `fk_chart_data_produk1_idx` (`data_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_chart_data_produk1`
    FOREIGN KEY (`data_produk_id`)
    REFERENCES `mydb`.`data_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `id` INT NOT NULL,
  `invoice_code` VARCHAR(45) NULL,
  `nama` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `data_produk_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_data_produk1_idx` (`data_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_data_produk1`
    FOREIGN KEY (`data_produk_id`)
    REFERENCES `mydb`.`data_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
